package ErrorUtils

func Throw(v uint) {
	panic(v)
}
